// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYMViP2E-6pwHkDmTdFx9xGYU6v88153A',
    appId: '1:118641844253:web:39c4bc80601a1ac017e6f4',
    messagingSenderId: '118641844253',
    projectId: 'psclearner-b8aa9',
    authDomain: 'psclearner-b8aa9.firebaseapp.com',
    storageBucket: 'psclearner-b8aa9.firebasestorage.app',
    measurementId: 'G-NEBPTENH1F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCiZpF6knQRKs1VQobKmTaA8JNacHCXvJ0',
    appId: '1:118641844253:android:28e4269b4eba68f717e6f4',
    messagingSenderId: '118641844253',
    projectId: 'psclearner-b8aa9',
    storageBucket: 'psclearner-b8aa9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUSO-UCF6xm6iRMTr_vflp3nfYC-dkjXY',
    appId: '1:118641844253:ios:8f3c9cf72b466df517e6f4',
    messagingSenderId: '118641844253',
    projectId: 'psclearner-b8aa9',
    storageBucket: 'psclearner-b8aa9.firebasestorage.app',
    iosBundleId: 'com.example.pscLearner',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCUSO-UCF6xm6iRMTr_vflp3nfYC-dkjXY',
    appId: '1:118641844253:ios:8f3c9cf72b466df517e6f4',
    messagingSenderId: '118641844253',
    projectId: 'psclearner-b8aa9',
    storageBucket: 'psclearner-b8aa9.firebasestorage.app',
    iosBundleId: 'com.example.pscLearner',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAYMViP2E-6pwHkDmTdFx9xGYU6v88153A',
    appId: '1:118641844253:web:5776c8a40ef8241217e6f4',
    messagingSenderId: '118641844253',
    projectId: 'psclearner-b8aa9',
    authDomain: 'psclearner-b8aa9.firebaseapp.com',
    storageBucket: 'psclearner-b8aa9.firebasestorage.app',
    measurementId: 'G-CS8R0BXSED',
  );
}
